expose anzu--update-timer to the user
emacsorphanage/anzu pull request #125
Opened 2023-10-18 18:50 UTC by LemonBreezes

Hello. This PR exposes `anzu--update-timer' to the user so that I can call its lambda manually from Elisp. 

The idea is that I want to use Corfu to complete search queries in the minibuffer and to do so, I must be able to manually update the visual hint because completion & `minibuffer-exit` happen simultaneously (no time for an idle timer).
![image](https://github.com/emacsorphanage/anzu/assets/29102529/60295cf9-845c-4c36-ba39-c45364e4e643)

2024-01-06 15:20 UTC, tarsius commented
I was asked to review this by mail, by @LemonBreezes.

@gonewest818, you volunteered as the new maintainer of this package. Are you still interested in this position? If so, then please have a look at this pull-request.

@LemonBreezes, if we don't hear from @gonewest818 in a week or two, then please ping me and I will do the review then. Sorry for the delay, and thanks for your patience!

2024-02-01 19:40 UTC, LemonBreezes commented
> I was asked to review this by mail, by @LemonBreezes.
> 
> @gonewest818, you volunteered as the new maintainer of this package. Are you still interested in this position? If so, then please have a look at this pull-request.
> 
> @LemonBreezes, if we don't hear from @gonewest818 in a week or two, then please ping me and I will do the review then. Sorry for the delay, and thanks for your patience!

Thanks for the response, @tarsius. Sure!

2024-02-01 20:38 UTC, tarsius commented
I've [read](https://www.reddit.com/r/emacs/comments/1afr34c/i_love_magit_forges/koh9q55/) that #246 makes this package usable again.

2024-02-01 20:50 UTC, tarsius requested changes

2024-02-01 20:50 UTC, tarsius commented on anzu.el
> +                (setq anzu--update-timer (run-with-idle-timer
Please reindent below.

2024-02-01 20:50 UTC, tarsius commented on anzu.el
> +                (setq anzu--update-timer (run-with-idle-timer
Here too.

2024-02-01 20:53 UTC, tarsius commented
> By the way, if you want, I can maintain this package.

I've given you commit access. Thanks for volunteering!

Please review the other pull-request too. It looks okay to me.

2024-02-01 23:15 UTC, LemonBreezes commented
> > By the way, if you want, I can maintain this package.
> 
> I've given you commit access. Thanks for volunteering!
> 
> Please review the other pull-request too. It looks okay to me.

Sure. Also, I just resolved the indentation issue.

2024-02-02 00:27 UTC, tarsius approved these changes

2024-02-02 00:32 UTC, merged